INSERT INTO "t_detailsptbphtb" ("t_idspt", 
"t_nikwppembeli", "t_namawppembeli", "t_alamatwppembeli", 
"provinsipembeli", "t_kecamatanwppembeli", "t_kelurahanwppembeli", 
"t_kabkotawppembeli", "t_telponwppembeli", "t_kodeposwppembeli", 
"t_npwpwppembeli", "t_rwwppembeli", "t_rtwppembeli", "t_nikwppenjual", 
"t_namawppenjual", "provinsipenjual", "t_kecamatanwppenjual", 
"t_kelurahanwppenjual", "t_kabkotawppenjual", "t_rwwppenjual", 
"t_rtwppenjual", "t_telponwppenjual", "t_kodeposwppenjual",
 "t_npwpwppenjual", "t_alamatwppenjual", "t_luastanah", 
 "t_njoptanah", "t_luasbangunan", "t_njopbangunan", "t_totalnjoptanah", 
 "t_totalnjopbangunan", "t_luastanah_sppt", "t_njoptanah_sppt", "t_luasbangunan_sppt", 
 "t_njopbangunan_sppt", "t_totalnjoptanah_sppt", "t_totalnjopbangunan_sppt", 
 "t_grandtotalnjop", "t_nosertifikathaktanah", "t_tglajb", "t_tglajbbaru", 
 "t_noajbbaru", "t_kelurahanop", "t_kecamatanop", "t_ketwaris", "t_terbukti", 
 "t_alamatop", "t_rtop", "t_rwop", "t_namasppt", "t_kabupatenop", "t_namasertifikat")
  VALUES (7, '7403347112680005', 'SARNA, S.PD', 'DESA LANOBAKE', '74', '7402112', '7402112003',
   '7402', '', '', '__.___.___._-___.___', '000', '000', '123456789', 'LA HADI', '74', '7409120', '7409120006', 
   '7409', '000', '000', '', '', '0_.___.___._-___.___', 'JLN KERATON', '11500', '7150', '', '', '82225000', '0', '', '', '', '', '0', '0', '82225000', '00570', '2011-11-15', '1970-01-01', '', 
'LIPU', 'KULISUSU', '', NULL, 'KADACUA', '000', '000', 'SARNAA', 'BUTON UTARA', 'LA HADI')